"""Repository protocols 
"""
from typing import Protocol


class UserRepo(Protocol):
    def get_by_email(self, email: str) -> dict | None: ...
    def get_by_id(self, user_id: str) -> dict | None: ...
    def create(self, user: dict) -> dict: ...
    def list(self) -> list[dict]: ...
    def update(self, user_id: str, patch: dict) -> dict | None: ...
    def touch_last_seen(self, user_id: str, when: str) -> None: ...


class OrderRepo(Protocol):
    def add(self, order: dict) -> dict: ...
    def list_for_user(self, user_id: str) -> list[dict]: ...


class HoldingRepo(Protocol):
    def list_for_user(self, user_id: str) -> list[dict]: ...
    def get_cash(self, user_id: str) -> float: ...
    def set_cash(self, user_id: str, amount: float) -> None: ...
    def upsert(self, user_id: str, symbol: str, qty: int, avg_cost: float) -> None: ...


class DatasetRepo(Protocol):
    def list(self) -> list[dict]: ...
    def create(self, dataset: dict) -> dict: ...
    def delete(self, dataset_id: str) -> bool: ...


class MarketRepo(Protocol):
    def list_tickers(self) -> list[dict]: ...
    def get_series(self, symbol: str, range_: str) -> list[dict]: ...
    def get_quote(self, symbol: str) -> dict | None: ...
    def get_market_quotes(self) -> list[dict]: ...


class PredictionRepo(Protocol):
    def get(self, symbol: str) -> dict | None: ...
    def get_backtest(self, symbol: str) -> dict | None: ...
    def get_forecast_log(self, symbol: str) -> list[dict]: ...
